library(tm)
library(wordcloud)
library(RColorBrewer)
speech= "reduced.txt"
modi_txt<-readLines(speech)
modi<-Corpus(VectorSource(modi_txt))
modi_data<-tm_map(modi,stripWhitespace)
modi_data<-tm_map(modi_data,tolower)
modi_data<-tm_map(modi_data,removeNumbers)
modi_data<-tm_map(modi_data,removePunctuation)
modi_data<-tm_map(modi_data,removeWords, stopwords("english"))
modi_data<-tm_map(modi_data,removeWords, c("and","the","our","that","for","are","also","more","has","must","have","should","this","with","system"))
modi_data <- tm_map(modi_data, PlainTextDocument)
wordcloud(modi_data, scale=c(5,0.5), max.words=50, random.order=FALSE, rot.per=0.35, use.r.layout=FALSE, colors=brewer.pal(8, "Dark2"))
